project_id = "qvfhieihrshgcljngpcq"

[functions.telegram-support]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.admin-products]
verify_jwt = true

[functions.squid-game-bot]
verify_jwt = false

[functions.casino-auth]
verify_jwt = false
